remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - stable=https://charts.helm.sh/stable
  - postgres=https://charts.bitnami.com/bitnami
  - yugabyte=https://charts.yugabyte.com
  - windmill=https://windmill-labs.github.io/windmill-helm-charts
helm-extra-args: --timeout=600s
